# [module.hugoVersion]
# min = "0.111.3"

[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hbstack/bigger-picture"

[[module.imports]]
path = "github.com/hbstack/bs-tooltip"

[params.hb.gallery]
paginate = 24
# Thumbnail size in form [width]x[height].
# - [width]x[height]: resize to given [width] and [height], such as 1280x720.
# - [width]x: resize to a width of [width]px and preserve aspect ratio, such as 1280x.
# - x[height]: resize to a height of [height]px and preserve aspect ratio, such as x640.
thumbnail_size = "x640"
